language: cpp

# Compiler and OS selection.
compiler:
- clang
- gcc
os:
- linux
# Note: Xcode is badly outdated right now. https://docs.travis-ci.com/user/osx-ci-environment
- osx
matrix:
  exclude:
    - compiler: gcc
    - os: osx
# See: https://docs.travis-ci.com/user/ci-environment/
# Ubuntu 14.04 is much more relevant to Gosu than 12.04 is.
sudo: required
dist: trusty

# Linux dependencies
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libpango1.0-dev
      - libgl1-mesa-dev
      - libfreeimage-dev
      - libopenal-dev
      # See: https://github.com/travis-ci/apt-package-whitelist/issues/2859
      # - libsndfile-dev
before_install:
  - gem install rake-compiler
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install sdl2; fi
  # TODO: Remove once we have access to the libsndfile-dev package.
  - if [ $TRAVIS_OS_NAME == linux ]; then wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.26.tar.gz && tar -xzvf libsndfile-1.0.26.tar.gz && cd libsndfile-1.0.26 && ./configure --prefix=/usr && make && sudo make install; fi

# Minimal git coverage (for now).
branches:
  only:
  - master
git:
  depth: 3

# 'rake gem' relies on this.
env:
  global:
    - GOSU_RELEASE_VERSION=9.9.9

install: rake gem && cd "$TRAVIS_BUILD_DIR" && gem install pkg/gosu-9.9.9.gem
script: ruby -rgosu -e 'puts Gosu::VERSION'
