language: cpp

matrix:
  include:
    # Ubuntu 14.04 Trusty Tahr
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    # OS X 10.9 Mavericks
    - os: osx
      osx_image: beta-xcode6.2
      compiler: clang
    # OS X 10.11 El Capitan
    - os: osx
      osx_image: xcode7.3
      compiler: clang

# Linux dependencies
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libpango1.0-dev
      - libgl1-mesa-dev
      - libfreeimage-dev
      - libopenal-dev
      # See: https://github.com/travis-ci/apt-package-whitelist/issues/2859
      # - libsndfile-dev
before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; brew install sdl2; rvm use 2.1; fi
  - gem update --system && gem install rake-compiler
  # TODO: Remove once we have access to the libsndfile-dev package.
  - if [ $TRAVIS_OS_NAME == linux ]; then wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.26.tar.gz && tar -xzvf libsndfile-1.0.26.tar.gz && cd libsndfile-1.0.26 && ./configure --prefix=/usr && make && sudo make install; fi

# Minimal git coverage (for now).
branches:
  only:
  - master
git:
  depth: 3

# 'rake gem' relies on this.
env:
  global:
    - GOSU_RELEASE_VERSION=9.9.9

notifications:
  email:
    - info@libgosu.org

install: rake gem && cd "$TRAVIS_BUILD_DIR" && gem install pkg/gosu-9.9.9.gem
script: ruby -rgosu -e 'puts Gosu::VERSION'
